[package]
name = "sss_lib"
version = "0.1.4"
publish = false
dist = false
repository.workspace = true
homepage.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
clap.workspace = true
serde.workspace = true
merge2.workspace = true
tracing.workspace = true
thiserror.workspace = true
conv = "0.3.3"
font-kit = "0.13.2"
pathfinder_geometry = "0.5.1"
imageproc = "0.25.0"
arboard = { version = "3.4.0", features = ["wayland-data-control"] }
image = { version = "0.24.7", default-features = false, features = [
    "png",
    "jpeg",
    "jpeg_rayon",
    "webp",
] }
rayon = "1.8.0"
notify-rust = { version = "4.10.0", features = ["images"] }
