name: "Check flake & Push built packages to cache"

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - web/
      - .gitignore
      - README.md
      - release.toml

env:
  PROJECT_NAME: sss

jobs:
  check-flake:
    name: "Check flake validity"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          logger: pretty

      - name: Check Flake
        run: nix flake check --accept-flake-config

  cachix:
    name: "Build & Cache Exposed Packages"
    runs-on: ubuntu-latest
    needs: check-flake
    strategy:
      matrix:
        package:
          - cli
          - code
    steps:
      - uses: easimon/maximize-build-space@v8
        with:
          overprovision-lvm: true
          remove-android: true
          remove-dotnet: true
          remove-haskell: true
          remove-docker-images: true
          remove-codeql: true

      - name: Checkout
        uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v26
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - uses: cachix/cachix-action@v14
        with:
          authToken: ${{ secrets.CACHIX_TOKEN }}
          name: ${{ env.PROJECT_NAME }}

      - name: Build from the defined matrix
        run: nix build .#${{ matrix.package }} --print-build-logs --extra-substituters "https://${{ env.PROJECT_NAME }}.cachix.org"
